title: "Ben Adler"
description: 
nav_pages: 
 - 
#theme: minima
remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme
author: ""
kramdown:
  parse_block_html: true
  input: GFM

# Minima 3.0 features (from master branch)
minima:
  skin: auto  # Options: auto, classic, dark, solarized, solarized-dark
